version: '3'

services:
  backend:
    platform: linux/amd64
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: infisical/backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/nodemon.json:/app/nodemon.json
      - /app/node_modules
    command: npm run start
    env_file: .env
    networks:
      - infisical
  
  frontend:
    platform: linux/amd64
    container_name: infisical-frontend
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: infisical/frontend
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
      - ./frontend/components:/app/components
      - ./frontend/next.config.js:/app/next.config.js
    env_file: .env
    networks:
      - infisical

  mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - infisical

volumes:
  mongo-data:
    driver: local